"""Storage and access layer: every component reads telemetry, events and state from here.

DuckDB queries parquet files in place, so there is no database server and no import step.
Nothing in this package computes physics, features or scores — it only moves data.
"""

from __future__ import annotations

from rai.store.events import (
    events_available,
    events_in_window,
    load_events,
    load_events_df,
    write_events,
)
from rai.store.state import (
    artifact_path,
    artifact_root,
    asset_state_path,
    clear_asset_states,
    list_cached_states,
    load_all_asset_states,
    load_asset_state,
    load_json_artifact,
    save_asset_state,
    save_json_artifact,
    set_artifact_root,
    state_dir,
)
from rai.store.telemetry import (
    ASSET_COLUMN,
    TS_COLUMN,
    DataUnavailable,
    asset_parquet_path,
    available_columns,
    connection,
    data_extent,
    data_root,
    events_path,
    latest_row,
    list_assets_with_data,
    load_fleet_latest,
    load_site_met,
    load_telemetry,
    load_window,
    resample,
    reset_connection,
    row_count,
    set_data_root,
    site_met_path,
    telemetry_available,
    telemetry_dir,
    write_site_met,
    write_telemetry,
)

__all__ = [
    "ASSET_COLUMN",
    "TS_COLUMN",
    "DataUnavailable",
    "artifact_path",
    "artifact_root",
    "asset_parquet_path",
    "asset_state_path",
    "available_columns",
    "clear_asset_states",
    "connection",
    "data_extent",
    "data_root",
    "events_available",
    "events_in_window",
    "events_path",
    "latest_row",
    "list_assets_with_data",
    "list_cached_states",
    "load_all_asset_states",
    "load_asset_state",
    "load_events",
    "load_events_df",
    "load_fleet_latest",
    "load_json_artifact",
    "load_site_met",
    "load_telemetry",
    "load_window",
    "resample",
    "reset_connection",
    "row_count",
    "save_asset_state",
    "save_json_artifact",
    "set_artifact_root",
    "set_data_root",
    "site_met_path",
    "state_dir",
    "telemetry_available",
    "telemetry_dir",
    "write_events",
    "write_site_met",
    "write_telemetry",
]
